version: '3.6'

services:
  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USE_SECRETS=true
    volumes:
      - ~/.microsoft/usersecrets/ff1a56b8-c5a3-4c4a-8202-0e2ffa9c6a3f:/app/UserSecrets