version: '3.6'

services:
  identityservice:
    container_name: IdentityService
    image: identityservice
    hostname: identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    depends_on:
      - identityservicemongodb
    ports:
      - 3004:80

  identityservicemongodb:
    container_name: IdentityServiceDB
    image: mongo:latest
    hostname: identityservicemongodb
    ports:
      - 27017:27017